"""Tests for MI-Workbench Reproducibility Package generator and API."""
from __future__ import annotations

import io
import json
import os
import tempfile
import zipfile
from pathlib import Path

import pytest
from httpx import AsyncClient

from backend.repropack.generator import ReproPackGenerator

pytestmark = pytest.mark.asyncio

# ── Fixtures ────────────────────────────────────────────────────────


@pytest.fixture
def sample_run_dir(tmp_path: Path) -> Path:
    """Create a temporary run directory with sample artifacts."""
    run_dir = tmp_path / "runs" / "test_run_001"
    run_dir.mkdir(parents=True)

    # Artifact files
    (run_dir / "MECH.md").write_text("# Mechanistic Analysis\n\nSample content.")
    (run_dir / "EVAL.md").write_text("# Evaluation Report\n\nAll tests passed.")
    (run_dir / "XP.md").write_text("# Experiment Plan\n\nStep 1: do the thing.")
    (run_dir / "METHOD.md").write_text("# Methodology\n\nUsed Geneformer V2.")
    (run_dir / "results.json").write_text(json.dumps({"auroc": 0.743, "p_value": 0.017}))

    # run_meta.json
    (run_dir / "run_meta.json").write_text(json.dumps({
        "run_id": "test_run_001",
        "workspace_id": "ws001",
        "provider": "mock",
        "model": "test-model",
        "loop_preset": "executor_reviewer",
        "task": "Test reproducibility",
        "started_at": "2026-01-01T00:00:00",
        "completed_at": "2026-01-01T01:00:00",
        "total_iterations": 3,
        "total_tokens": 5000,
        "total_cost": 0.50,
        "status": "completed",
        "prompts_used": {"executor": "mi_executor v1.0"},
    }))

    # Log files
    logs_dir = run_dir / "logs"
    logs_dir.mkdir()
    (logs_dir / "iteration_1.log").write_text("Started iteration 1\nCompleted.")
    (logs_dir / "iteration_2.log").write_text("Started iteration 2\nCompleted.")

    return run_dir


@pytest.fixture
def workspace_path(tmp_path: Path) -> str:
    """Return a workspace path (not a real git repo)."""
    ws = tmp_path / "workspace"
    ws.mkdir()
    return str(ws)


@pytest.fixture
def generator() -> ReproPackGenerator:
    return ReproPackGenerator()


# ── Generator unit tests ────────────────────────────────────────────


def test_generate_creates_valid_zip(
    generator: ReproPackGenerator,
    sample_run_dir: Path,
    workspace_path: str,
) -> None:
    """The generated bytes are a valid zip archive."""
    zip_bytes = generator.generate(str(sample_run_dir), workspace_path)
    assert isinstance(zip_bytes, bytes)
    assert len(zip_bytes) > 0
    # Should be a valid zip
    buf = io.BytesIO(zip_bytes)
    with zipfile.ZipFile(buf, "r") as zf:
        assert zf.testzip() is None  # no corrupt files


def test_zip_contains_artifacts(
    generator: ReproPackGenerator,
    sample_run_dir: Path,
    workspace_path: str,
) -> None:
    """Artifacts from the run directory appear in artifacts/."""
    zip_bytes = generator.generate(str(sample_run_dir), workspace_path)
    buf = io.BytesIO(zip_bytes)
    with zipfile.ZipFile(buf, "r") as zf:
        names = zf.namelist()
        assert "artifacts/MECH.md" in names
        assert "artifacts/EVAL.md" in names
        assert "artifacts/XP.md" in names
        assert "artifacts/results.json" in names
        # Verify content
        mech = zf.read("artifacts/MECH.md").decode()
        assert "Mechanistic Analysis" in mech


def test_zip_contains_environment_info(
    generator: ReproPackGenerator,
    sample_run_dir: Path,
    workspace_path: str,
) -> None:
    """metadata/environment.json exists and has expected keys."""
    zip_bytes = generator.generate(str(sample_run_dir), workspace_path)
    buf = io.BytesIO(zip_bytes)
    with zipfile.ZipFile(buf, "r") as zf:
        assert "metadata/environment.json" in zf.namelist()
        env = json.loads(zf.read("metadata/environment.json"))
        assert "python_version" in env
        assert "platform" in env
        assert "os" in env
        assert "captured_at" in env


def test_zip_contains_readme(
    generator: ReproPackGenerator,
    sample_run_dir: Path,
    workspace_path: str,
) -> None:
    """README.md exists and contains run information."""
    zip_bytes = generator.generate(str(sample_run_dir), workspace_path)
    buf = io.BytesIO(zip_bytes)
    with zipfile.ZipFile(buf, "r") as zf:
        assert "README.md" in zf.namelist()
        readme = zf.read("README.md").decode()
        assert "Reproducibility Package" in readme
        assert "test_run_001" in readme
        assert "Package Contents" in readme


def test_zip_contains_reproducibility_checklist(
    generator: ReproPackGenerator,
    sample_run_dir: Path,
    workspace_path: str,
) -> None:
    """methods/reproducibility_checklist.md exists and has checklist items."""
    zip_bytes = generator.generate(str(sample_run_dir), workspace_path)
    buf = io.BytesIO(zip_bytes)
    with zipfile.ZipFile(buf, "r") as zf:
        assert "methods/reproducibility_checklist.md" in zf.namelist()
        checklist = zf.read("methods/reproducibility_checklist.md").decode()
        assert "Reproducibility Checklist" in checklist
        assert "- [ ]" in checklist
        assert "environment.json" in checklist
        assert "git_state.json" in checklist


def test_zip_contains_dataset_card(
    generator: ReproPackGenerator,
    sample_run_dir: Path,
    workspace_path: str,
) -> None:
    """methods/dataset_card.md exists."""
    zip_bytes = generator.generate(str(sample_run_dir), workspace_path)
    buf = io.BytesIO(zip_bytes)
    with zipfile.ZipFile(buf, "r") as zf:
        assert "methods/dataset_card.md" in zf.namelist()
        card = zf.read("methods/dataset_card.md").decode()
        assert "Dataset Card" in card
        assert "Available Artifacts" in card


def test_zip_contains_logs(
    generator: ReproPackGenerator,
    sample_run_dir: Path,
    workspace_path: str,
) -> None:
    """Log files from the run are included under logs/."""
    zip_bytes = generator.generate(str(sample_run_dir), workspace_path)
    buf = io.BytesIO(zip_bytes)
    with zipfile.ZipFile(buf, "r") as zf:
        names = zf.namelist()
        assert "logs/iteration_1.log" in names
        assert "logs/iteration_2.log" in names


def test_zip_contains_method_md(
    generator: ReproPackGenerator,
    sample_run_dir: Path,
    workspace_path: str,
) -> None:
    """METHOD.md from the run directory is included under methods/."""
    zip_bytes = generator.generate(str(sample_run_dir), workspace_path)
    buf = io.BytesIO(zip_bytes)
    with zipfile.ZipFile(buf, "r") as zf:
        assert "methods/METHOD.md" in zf.namelist()
        method = zf.read("methods/METHOD.md").decode()
        assert "Geneformer V2" in method


def test_zip_contains_metadata_files(
    generator: ReproPackGenerator,
    sample_run_dir: Path,
    workspace_path: str,
) -> None:
    """All metadata files are present."""
    zip_bytes = generator.generate(str(sample_run_dir), workspace_path)
    buf = io.BytesIO(zip_bytes)
    with zipfile.ZipFile(buf, "r") as zf:
        names = zf.namelist()
        assert "metadata/run_meta.json" in names
        assert "metadata/prompts_used.json" in names
        assert "metadata/environment.json" in names
        assert "metadata/git_state.json" in names
        assert "metadata/timestamps.json" in names

        # Verify run_meta content
        meta = json.loads(zf.read("metadata/run_meta.json"))
        assert meta["run_id"] == "test_run_001"
        assert meta["task"] == "Test reproducibility"

        # Verify git_state has expected structure
        git = json.loads(zf.read("metadata/git_state.json"))
        assert "is_git_repo" in git or "workspace_path" in git


def test_preview_lists_files(
    generator: ReproPackGenerator,
    sample_run_dir: Path,
    workspace_path: str,
) -> None:
    """Preview returns a list of files that would be in the zip."""
    files = generator.preview(str(sample_run_dir), workspace_path)
    assert isinstance(files, list)
    assert len(files) > 0

    paths = [f["path"] for f in files]
    # Should include artifacts
    assert "artifacts/MECH.md" in paths
    assert "artifacts/EVAL.md" in paths
    # Should include logs
    assert "logs/iteration_1.log" in paths
    # Should include metadata
    assert "metadata/run_meta.json" in paths
    assert "metadata/environment.json" in paths
    # Should include methods
    assert "methods/METHOD.md" in paths
    assert "methods/dataset_card.md" in paths
    assert "methods/reproducibility_checklist.md" in paths
    assert "README.md" in paths

    # Each entry has path and size
    for f in files:
        assert "path" in f
        assert "size" in f


# ── API endpoint tests ──────────────────────────────────────────────


async def test_api_endpoint_returns_zip(client: AsyncClient) -> None:
    """POST /api/repropack/{run_id} returns a zip file."""
    # Create workspace and run
    ws_resp = await client.post("/api/workspaces", json={
        "name": "ws-repro",
        "path": "/tmp/ws-repro-test",
    })
    ws_id = ws_resp.json()["id"]

    run_resp = await client.post("/api/runs", json={
        "workspace_id": ws_id,
        "task": "Test repropack API",
        "provider": "mock",
    })
    run_id = run_resp.json()["run_id"]

    # Generate repro pack
    resp = await client.post(f"/api/repropack/{run_id}")
    assert resp.status_code == 200
    assert resp.headers["content-type"] == "application/zip"
    assert f"repropack-{run_id}" in resp.headers.get("content-disposition", "")

    # Verify it's a valid zip
    buf = io.BytesIO(resp.content)
    with zipfile.ZipFile(buf, "r") as zf:
        assert zf.testzip() is None
        names = zf.namelist()
        assert "README.md" in names
        assert "metadata/run_meta.json" in names
        assert "metadata/environment.json" in names
        assert "methods/reproducibility_checklist.md" in names


async def test_api_preview_endpoint(client: AsyncClient) -> None:
    """GET /api/repropack/{run_id}/preview returns file list."""
    ws_resp = await client.post("/api/workspaces", json={
        "name": "ws-repro-preview",
        "path": "/tmp/ws-repro-preview-test",
    })
    ws_id = ws_resp.json()["id"]

    run_resp = await client.post("/api/runs", json={
        "workspace_id": ws_id,
        "task": "Test preview",
        "provider": "mock",
    })
    run_id = run_resp.json()["run_id"]

    resp = await client.get(f"/api/repropack/{run_id}/preview")
    assert resp.status_code == 200
    data = resp.json()
    assert "run_id" in data
    assert data["run_id"] == run_id
    assert "files" in data
    assert "total_files" in data
    assert isinstance(data["files"], list)
    assert data["total_files"] > 0


async def test_api_repropack_run_not_found(client: AsyncClient) -> None:
    """POST /api/repropack/{run_id} returns 404 for nonexistent run."""
    resp = await client.post("/api/repropack/nonexistent_run")
    assert resp.status_code == 404


# ── Iteration directories and persisted execution outputs ──────────


def _write(path: Path, content) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    if isinstance(content, bytes):
        path.write_bytes(content)
    else:
        path.write_text(content)
    return path


@pytest.fixture
def full_run(tmp_path: Path):
    """A run directory with iteration dirs and persisted execution outputs."""
    run_dir = tmp_path / "ws" / "runs" / "run_full"
    persist = tmp_path / "persist"
    unit = persist / "20261001T120000_aaaa1111"
    other_unit = persist / "20261001T120500_bbbb2222"   # another run's unit (not listed)
    outside = tmp_path / "secrets"
    _write(outside / "id_rsa", "PRIVATE")
    _write(unit / "code.py", "print('hi')\n")
    _write(unit / "stdout.txt", "hi\n" * 1000)
    _write(unit / "stderr.txt", "")
    _write(unit / "work" / "results.json", json.dumps({"auroc": 0.74}))
    _write(unit / "work" / "big.bin", b"\0" * (2 * 1024 * 1024))     # above a 1 MB cap
    _write(other_unit / "code.py", "print('other run')\n")

    _write(run_dir / "MECH.md", "# top-level MECH")
    it1 = run_dir / "iter_0001"
    _write(it1 / "executor_output.md", "# MECH.md\nfull executor output")
    _write(it1 / "MECH.md", "# MECH parsed")
    _write(it1 / "RUN_LOG.md", "=== CODE EXECUTION REPORT ===")
    _write(it1 / "figure.png", bytes(range(256)))
    _write(it1 / "._MECH.md", b"\x00\x05\x16\x07AppleDouble")
    _write(it1 / "CODE_EXECUTION.json", json.dumps({
        "iteration": 1, "executed": 2,
        "blocks": [{"index": 0, "persisted_to": str(unit)},
                   {"index": 1, "persisted_to": str(outside)}],
    }))
    it2 = run_dir / "iter_0002"
    _write(it2 / "consensus_merger_output.md", "merged feedback")
    _write(it2 / "EVAL.md", "merged feedback")
    _write(it2 / "CONSENSUS.json", json.dumps({"iteration": 2, "grade": "B"}))
    _write(it2 / "reviewer_output.md", "[HIGH] x")
    _write(it2 / "consensus_merger_feedback.md", "feedback for the executor")
    _write(it2 / "nested" / "lens.txt", "nested file")
    os.symlink(outside / "id_rsa", it2 / "leak.txt")
    meta = {"run_id": "run_full", "task": "t", "provider": "mock", "status": "completed",
            "config": {"code_execution_persist_dir": str(persist)}}
    _write(run_dir / "run_meta.json", json.dumps(meta))
    return run_dir, unit, other_unit, outside


def _zip(data: bytes) -> zipfile.ZipFile:
    return zipfile.ZipFile(io.BytesIO(data), "r")


def test_every_iteration_directory_is_packaged(full_run, workspace_path):
    run_dir = full_run[0]
    zf = _zip(ReproPackGenerator(max_file_mb=1).generate(str(run_dir), workspace_path))
    names = set(zf.namelist())
    for d in ("iter_0001", "iter_0002"):
        for f in (run_dir / d).rglob("*"):
            if f.is_file() and not f.is_symlink() and not f.name.startswith("._"):
                arc = f"iterations/{d}/{f.relative_to(run_dir / d).as_posix()}"
                assert arc in names, arc
                assert zf.read(arc) == f.read_bytes()           # byte-identical
    for required in ("iterations/iter_0001/executor_output.md",
                     "iterations/iter_0001/CODE_EXECUTION.json",
                     "iterations/iter_0001/RUN_LOG.md",
                     "iterations/iter_0002/CONSENSUS.json",
                     "iterations/iter_0002/consensus_merger_feedback.md",
                     "iterations/iter_0002/nested/lens.txt"):
        assert required in names
    assert zf.read("iterations/iter_0001/figure.png") == bytes(range(256))
    assert "artifacts/MECH.md" in names                       # top-level files still there
    assert not any(n.endswith("._MECH.md") for n in names)    # AppleDouble metadata skipped
    assert "iterations/iter_0002/leak.txt" not in names       # symlink never followed
    assert not any("PRIVATE" in zf.read(n).decode(errors="ignore") for n in names)


def test_persisted_execution_outputs_are_packaged_with_a_size_cap(full_run, workspace_path):
    run_dir, unit, other_unit, outside = full_run
    zf = _zip(ReproPackGenerator(max_file_mb=1).generate(str(run_dir), workspace_path))
    names = set(zf.namelist())
    prefix = f"code_execution/iter_0001/{unit.name}"
    for rel in ("code.py", "stdout.txt", "stderr.txt", "work/results.json"):
        assert f"{prefix}/{rel}" in names
        assert zf.read(f"{prefix}/{rel}") == (unit / rel).read_bytes()
    assert f"{prefix}/work/big.bin" not in names                   # above the cap
    assert not any(other_unit.name in n for n in names)            # not this run's unit
    assert not any("secrets" in n or "id_rsa" in n for n in names)  # outside the persist dir
    readme = zf.read("README.md").decode()
    assert "## Files not included" in readme
    assert f"`{prefix}/work/big.bin`" in readme and "per-file cap" in readme
    assert "outside the run's code_execution_persist_dir" in readme
    assert "iterations/iter_0002/leak.txt" in readme and "not a regular file" in readme
    assert "Per-file size cap: 1.0 MB" in readme


def test_size_cap_is_configurable(full_run, workspace_path, monkeypatch):
    run_dir, unit, _, _ = full_run
    big = f"code_execution/iter_0001/{unit.name}/work/big.bin"
    uncapped = _zip(ReproPackGenerator().generate(str(run_dir), workspace_path, max_file_mb=0))
    assert big in uncapped.namelist()
    assert "Files not included" in uncapped.read("README.md").decode()
    monkeypatch.setenv("MIW_REPROPACK_MAX_FILE_MB", "0.5")
    gen = ReproPackGenerator()
    assert gen.max_file_mb == 0.5
    capped = _zip(gen.generate(str(run_dir), workspace_path))
    assert big not in capped.namelist()
    assert f"code_execution/iter_0001/{unit.name}/stdout.txt" in capped.namelist()  # 3 KB
    with pytest.raises(ValueError):
        ReproPackGenerator(max_file_mb=-1)


def test_preview_lists_iterations_and_skipped_files(full_run, workspace_path):
    run_dir, unit, _, _ = full_run
    files = ReproPackGenerator(max_file_mb=1).preview(str(run_dir), workspace_path)
    by_path = {f["path"]: f for f in files}
    assert "iterations/iter_0002/CONSENSUS.json" in by_path
    assert f"code_execution/iter_0001/{unit.name}/code.py" in by_path
    assert "per-file cap" in by_path[f"code_execution/iter_0001/{unit.name}/work/big.bin"]["skipped"]


def test_persisted_outputs_need_a_recorded_persist_dir(full_run, workspace_path):
    run_dir, unit, _, _ = full_run
    meta = json.loads((run_dir / "run_meta.json").read_text())
    meta["config"] = {}
    (run_dir / "run_meta.json").write_text(json.dumps(meta))
    zf = _zip(ReproPackGenerator().generate(str(run_dir), workspace_path))
    assert not any(n.startswith("code_execution/") for n in zf.namelist())
    assert "code_execution_persist_dir is not recorded" in zf.read("README.md").decode()


async def test_repropack_of_a_real_run_with_persisted_execution(tmp_path):
    """End to end: a mock run with verified execution and a persist dir."""
    from unittest.mock import patch

    from backend.adapters.mock import MockAdapter
    from backend.config import config
    from backend.database import create_run, create_workspace, get_run, init_db
    from backend.models import ProviderName, RunState, WorkspaceConfig
    from backend.orchestrator import runner

    old_db = config.db_path
    config.db_path = str(tmp_path / "rp.db")
    try:
        await init_db()
        MockAdapter.reset_iteration_count()
        ws_dir = tmp_path / "ws"
        ws_dir.mkdir()
        ws = WorkspaceConfig(name="w", path=str(ws_dir), default_provider=ProviderName.MOCK)
        await create_workspace(ws)
        persist = tmp_path / "persist"
        run = RunState(workspace_id=ws.id, loop_preset="executor_reviewer", task="t",
                       provider=ProviderName.MOCK, model="", max_iterations=3,
                       config={"convergence_enabled": False, "code_execution_enabled": True,
                               "code_execution_persist_dir": str(persist)})
        await create_run(run)
        with patch.object(runner, "get_adapter",
                          return_value=MockAdapter(min_delay=0, max_delay=0)):
            await runner.execute_run(run.run_id)
        final = await get_run(run.run_id)
        assert final.stop_reason == "max_iterations"
        run_dir = ws_dir / "runs" / run.run_id
        zf = _zip(ReproPackGenerator().generate(str(run_dir), str(ws_dir), run_state=final))
    finally:
        config.db_path = old_db
    names = set(zf.namelist())
    iter_dirs = sorted(d.name for d in run_dir.iterdir() if d.name.startswith("iter_"))
    assert iter_dirs == ["iter_0001", "iter_0002", "iter_0003"]
    for d in iter_dirs:
        for f in (run_dir / d).iterdir():
            if f.is_file() and not f.name.startswith("._"):
                assert f"iterations/{d}/{f.name}" in names
    assert "iterations/iter_0001/CODE_EXECUTION.json" in names
    assert "iterations/iter_0001/RUN_LOG.md" in names
    assert "iterations/iter_0002/reviewer_feedback.md" in names
    units = [p for p in persist.iterdir() if p.is_dir()]
    assert len(units) == 2                                        # executor iterations 1 and 3
    for u in units:
        assert any(n.endswith(f"{u.name}/code.py") for n in names)
        assert any(n.endswith(f"{u.name}/stdout.txt") for n in names)
    stdout = [n for n in names if n.startswith("code_execution/iter_0001/")
              and n.endswith("stdout.txt")][0]
    assert b"incremental_auroc" in zf.read(stdout)
