"""Tests for MI-Workbench Reproducibility Package generator and API."""
from __future__ import annotations

import io
import json
import os
import tempfile
import zipfile
from pathlib import Path

import pytest
from httpx import AsyncClient

from backend.repropack.generator import ReproPackGenerator

pytestmark = pytest.mark.asyncio

# ── Fixtures ────────────────────────────────────────────────────────


@pytest.fixture
def sample_run_dir(tmp_path: Path) -> Path:
    """Create a temporary run directory with sample artifacts."""
    run_dir = tmp_path / "runs" / "test_run_001"
    run_dir.mkdir(parents=True)

    # Artifact files
    (run_dir / "MECH.md").write_text("# Mechanistic Analysis\n\nSample content.")
    (run_dir / "EVAL.md").write_text("# Evaluation Report\n\nAll tests passed.")
    (run_dir / "XP.md").write_text("# Experiment Plan\n\nStep 1: do the thing.")
    (run_dir / "METHOD.md").write_text("# Methodology\n\nUsed Geneformer V2.")
    (run_dir / "results.json").write_text(json.dumps({"auroc": 0.743, "p_value": 0.017}))

    # run_meta.json
    (run_dir / "run_meta.json").write_text(json.dumps({
        "run_id": "test_run_001",
        "workspace_id": "ws001",
        "provider": "mock",
        "model": "test-model",
        "loop_preset": "executor_reviewer",
        "task": "Test reproducibility",
        "started_at": "2026-01-01T00:00:00",
        "completed_at": "2026-01-01T01:00:00",
        "total_iterations": 3,
        "total_tokens": 5000,
        "total_cost": 0.50,
        "status": "completed",
        "prompts_used": {"executor": "mi_executor v1.0"},
    }))

    # Log files
    logs_dir = run_dir / "logs"
    logs_dir.mkdir()
    (logs_dir / "iteration_1.log").write_text("Started iteration 1\nCompleted.")
    (logs_dir / "iteration_2.log").write_text("Started iteration 2\nCompleted.")

    return run_dir


@pytest.fixture
def workspace_path(tmp_path: Path) -> str:
    """Return a workspace path (not a real git repo)."""
    ws = tmp_path / "workspace"
    ws.mkdir()
    return str(ws)


@pytest.fixture
def generator() -> ReproPackGenerator:
    return ReproPackGenerator()


# ── Generator unit tests ────────────────────────────────────────────


def test_generate_creates_valid_zip(
    generator: ReproPackGenerator,
    sample_run_dir: Path,
    workspace_path: str,
) -> None:
    """The generated bytes are a valid zip archive."""
    zip_bytes = generator.generate(str(sample_run_dir), workspace_path)
    assert isinstance(zip_bytes, bytes)
    assert len(zip_bytes) > 0
    # Should be a valid zip
    buf = io.BytesIO(zip_bytes)
    with zipfile.ZipFile(buf, "r") as zf:
        assert zf.testzip() is None  # no corrupt files


def test_zip_contains_artifacts(
    generator: ReproPackGenerator,
    sample_run_dir: Path,
    workspace_path: str,
) -> None:
    """Artifacts from the run directory appear in artifacts/."""
    zip_bytes = generator.generate(str(sample_run_dir), workspace_path)
    buf = io.BytesIO(zip_bytes)
    with zipfile.ZipFile(buf, "r") as zf:
        names = zf.namelist()
        assert "artifacts/MECH.md" in names
        assert "artifacts/EVAL.md" in names
        assert "artifacts/XP.md" in names
        assert "artifacts/results.json" in names
        # Verify content
        mech = zf.read("artifacts/MECH.md").decode()
        assert "Mechanistic Analysis" in mech


def test_zip_contains_environment_info(
    generator: ReproPackGenerator,
    sample_run_dir: Path,
    workspace_path: str,
) -> None:
    """metadata/environment.json exists and has expected keys."""
    zip_bytes = generator.generate(str(sample_run_dir), workspace_path)
    buf = io.BytesIO(zip_bytes)
    with zipfile.ZipFile(buf, "r") as zf:
        assert "metadata/environment.json" in zf.namelist()
        env = json.loads(zf.read("metadata/environment.json"))
        assert "python_version" in env
        assert "platform" in env
        assert "os" in env
        assert "captured_at" in env


def test_zip_contains_readme(
    generator: ReproPackGenerator,
    sample_run_dir: Path,
    workspace_path: str,
) -> None:
    """README.md exists and contains run information."""
    zip_bytes = generator.generate(str(sample_run_dir), workspace_path)
    buf = io.BytesIO(zip_bytes)
    with zipfile.ZipFile(buf, "r") as zf:
        assert "README.md" in zf.namelist()
        readme = zf.read("README.md").decode()
        assert "Reproducibility Package" in readme
        assert "test_run_001" in readme
        assert "Package Contents" in readme


def test_zip_contains_reproducibility_checklist(
    generator: ReproPackGenerator,
    sample_run_dir: Path,
    workspace_path: str,
) -> None:
    """methods/reproducibility_checklist.md exists and has checklist items."""
    zip_bytes = generator.generate(str(sample_run_dir), workspace_path)
    buf = io.BytesIO(zip_bytes)
    with zipfile.ZipFile(buf, "r") as zf:
        assert "methods/reproducibility_checklist.md" in zf.namelist()
        checklist = zf.read("methods/reproducibility_checklist.md").decode()
        assert "Reproducibility Checklist" in checklist
        assert "- [ ]" in checklist
        assert "environment.json" in checklist
        assert "git_state.json" in checklist


def test_zip_contains_dataset_card(
    generator: ReproPackGenerator,
    sample_run_dir: Path,
    workspace_path: str,
) -> None:
    """methods/dataset_card.md exists."""
    zip_bytes = generator.generate(str(sample_run_dir), workspace_path)
    buf = io.BytesIO(zip_bytes)
    with zipfile.ZipFile(buf, "r") as zf:
        assert "methods/dataset_card.md" in zf.namelist()
        card = zf.read("methods/dataset_card.md").decode()
        assert "Dataset Card" in card
        assert "Available Artifacts" in card


def test_zip_contains_logs(
    generator: ReproPackGenerator,
    sample_run_dir: Path,
    workspace_path: str,
) -> None:
    """Log files from the run are included under logs/."""
    zip_bytes = generator.generate(str(sample_run_dir), workspace_path)
    buf = io.BytesIO(zip_bytes)
    with zipfile.ZipFile(buf, "r") as zf:
        names = zf.namelist()
        assert "logs/iteration_1.log" in names
        assert "logs/iteration_2.log" in names


def test_zip_contains_method_md(
    generator: ReproPackGenerator,
    sample_run_dir: Path,
    workspace_path: str,
) -> None:
    """METHOD.md from the run directory is included under methods/."""
    zip_bytes = generator.generate(str(sample_run_dir), workspace_path)
    buf = io.BytesIO(zip_bytes)
    with zipfile.ZipFile(buf, "r") as zf:
        assert "methods/METHOD.md" in zf.namelist()
        method = zf.read("methods/METHOD.md").decode()
        assert "Geneformer V2" in method


def test_zip_contains_metadata_files(
    generator: ReproPackGenerator,
    sample_run_dir: Path,
    workspace_path: str,
) -> None:
    """All metadata files are present."""
    zip_bytes = generator.generate(str(sample_run_dir), workspace_path)
    buf = io.BytesIO(zip_bytes)
    with zipfile.ZipFile(buf, "r") as zf:
        names = zf.namelist()
        assert "metadata/run_meta.json" in names
        assert "metadata/prompts_used.json" in names
        assert "metadata/environment.json" in names
        assert "metadata/git_state.json" in names
        assert "metadata/timestamps.json" in names

        # Verify run_meta content
        meta = json.loads(zf.read("metadata/run_meta.json"))
        assert meta["run_id"] == "test_run_001"
        assert meta["task"] == "Test reproducibility"

        # Verify git_state has expected structure
        git = json.loads(zf.read("metadata/git_state.json"))
        assert "is_git_repo" in git or "workspace_path" in git


def test_preview_lists_files(
    generator: ReproPackGenerator,
    sample_run_dir: Path,
    workspace_path: str,
) -> None:
    """Preview returns a list of files that would be in the zip."""
    files = generator.preview(str(sample_run_dir), workspace_path)
    assert isinstance(files, list)
    assert len(files) > 0

    paths = [f["path"] for f in files]
    # Should include artifacts
    assert "artifacts/MECH.md" in paths
    assert "artifacts/EVAL.md" in paths
    # Should include logs
    assert "logs/iteration_1.log" in paths
    # Should include metadata
    assert "metadata/run_meta.json" in paths
    assert "metadata/environment.json" in paths
    # Should include methods
    assert "methods/METHOD.md" in paths
    assert "methods/dataset_card.md" in paths
    assert "methods/reproducibility_checklist.md" in paths
    assert "README.md" in paths

    # Each entry has path and size
    for f in files:
        assert "path" in f
        assert "size" in f


# ── API endpoint tests ──────────────────────────────────────────────


async def test_api_endpoint_returns_zip(client: AsyncClient) -> None:
    """POST /api/repropack/{run_id} returns a zip file."""
    # Create workspace and run
    ws_resp = await client.post("/api/workspaces", json={
        "name": "ws-repro",
        "path": "/tmp/ws-repro-test",
    })
    ws_id = ws_resp.json()["id"]

    run_resp = await client.post("/api/runs", json={
        "workspace_id": ws_id,
        "task": "Test repropack API",
        "provider": "mock",
    })
    run_id = run_resp.json()["run_id"]

    # Generate repro pack
    resp = await client.post(f"/api/repropack/{run_id}")
    assert resp.status_code == 200
    assert resp.headers["content-type"] == "application/zip"
    assert f"repropack-{run_id}" in resp.headers.get("content-disposition", "")

    # Verify it's a valid zip
    buf = io.BytesIO(resp.content)
    with zipfile.ZipFile(buf, "r") as zf:
        assert zf.testzip() is None
        names = zf.namelist()
        assert "README.md" in names
        assert "metadata/run_meta.json" in names
        assert "metadata/environment.json" in names
        assert "methods/reproducibility_checklist.md" in names


async def test_api_preview_endpoint(client: AsyncClient) -> None:
    """GET /api/repropack/{run_id}/preview returns file list."""
    ws_resp = await client.post("/api/workspaces", json={
        "name": "ws-repro-preview",
        "path": "/tmp/ws-repro-preview-test",
    })
    ws_id = ws_resp.json()["id"]

    run_resp = await client.post("/api/runs", json={
        "workspace_id": ws_id,
        "task": "Test preview",
        "provider": "mock",
    })
    run_id = run_resp.json()["run_id"]

    resp = await client.get(f"/api/repropack/{run_id}/preview")
    assert resp.status_code == 200
    data = resp.json()
    assert "run_id" in data
    assert data["run_id"] == run_id
    assert "files" in data
    assert "total_files" in data
    assert isinstance(data["files"], list)
    assert data["total_files"] > 0


async def test_api_repropack_run_not_found(client: AsyncClient) -> None:
    """POST /api/repropack/{run_id} returns 404 for nonexistent run."""
    resp = await client.post("/api/repropack/nonexistent_run")
    assert resp.status_code == 404
